{% set version = "1.8.0" %}

package:
  name: libgsasl
  version: "{{ version }}"

source:
  fn: libgsasl-{{ version }}.tar.gz
  url: ftp://ftp.gnu.org/gnu/gsasl/libgsasl-{{ version }}.tar.gz
  sha256: 3adfb49f9c92a719dea855fd1840d698cde55d4648d332a69032ba8bea207720
  # See https://lists.gnu.org/archive/html/bug-gnulib/2017-07/msg00057.html
  patches:
    - vasnprintf-osx.patch  # [osx]

build:
  number: 1005
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}

  host:
    - libgcrypt
    - libntlm
    - krb5

  run:
    - libntlm
    - libgcrypt
    - krb5

test:
  commands:
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.7.dylib    # [osx]
    - test -f $PREFIX/lib/libgsasl.so.7.9.6   # [linux]

about:
  home: http://www.gnu.org/software/gsasl/
  license: LGPL-2.1
  license_file: 
    - COPYING 
    - COPYING.LIB 

  summary: Implementation of the Simple Authentication and Security Layer framework

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
