travis:
  secure:
    BINSTAR_TOKEN: ekXXHXWyi8YfLZ2bmbIY346nYyJQLROFDh9gwnHs3QfmkDUSjD3mGGzGVKwADL9k/XG9tmXQA5m4jiyBRrhH2FXpYa6Qmirr7VSNIk8gPMAUBrccyPxVxd6+MVpaHnS80D5uBFRwOWg+QEmKO0A4ApNrWdom/H2JKFkl21lo9Kx5Tohx+RUEl5xJjjPYAqd3lx2zsqY8OujNbCPSMiTKYgKKbskVySreLugeCNI1bbOSHRRHXy0z3Fj4FvArMQ0MLny4ibwiIPyIoGm0G2Kvrl3hU8Vtlm1lwF8NGpWZ+x/iiSFzzSkDNA3k34T/92c2LokYGmeuLInv8/3YAFyVaCIl/MNYZ186+NsmwEGnw9v0NuqrzSj/2GQae+zRfsX6CM6mKX8Jv1hIyO3vHHiAhVgzcE6nz7ZYuZGIJxSttEsYk0kX2khdhvXSCXhvshGf6p4CHBuPYkpO52R5C55KDpJXJA1KxIQuIAYpzt0r+SAiBb0KvrmyS8Iiw0Aq/GNXMqNne2RraxiBdj0VL2xmq27/EIBIdgnHvAJmWSyJ3h2oC+GTmGM9axRGcrGNWn3O/j3SJFkm2rDxcMx9LB+AAmuqS0gOwhIJ1L/rbmrFKMdTqMW5Ny+fwFNwUTTgW2MMDWx+VVKo5FBqNiO8X2ijeG9Tq2QoUO3IvrLwCLUmbfA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
