appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WdMBI6DQqtqy235ked0hqK6RhEowAjYNQz9vBTou6HuadCF+awh2+4uly2a9wbQgNkce21qx2RlkpMYTT3Px+/xX3CmbL/vzKGbDUOMv6Oj5/fUgI2NOvSEgaPXda0WNuHa1pVo67Rg9OOzM/+gLCr24Wk/mCXUmUIct8o51S/VxO64FxKLIHoNCi/IM1RCL9kOEckb/6NoDmSR4Mpg/2aTwkmMKPzvQBBW377lIcwR6LAyENqANJPamXzZFEo6WXMAV7VQ9h9Pj4DU2XcbgvuTVLc/TBSx7uRkktOjjOMg09uzRASSii6VP9W4teodjJjHxacGqTd4JGsIKntxMuXfKl84aoMZLcjza555/gAvSDA8vFCYBAvmfgLNoMp2PHL44tXf5eycSBlty0ltVaRXpiBsuBfdo+d8tLxvNSPhma1jyZQCNh8I9L1ZJFYEY4U7vV6b/3Cdhly7ORaHrmW1zLO+fH6cJWDAvB42KwqhOJKt5AhBPmKZLVvAaQS9pbWwwdIec/NMrMFVrZJqTS3lwKzsU+IxqRCzIznm8is3iZlqYd/+sLjr83kvOmKvaNdY7XYWDKT18Wo8ndFZTovhi9Lgmc/N1P9wqeqQKxFboCYBRSLa7gtEbkvlHyY72R50EAi7vOZmQbBLOaUo/LSXEN6uB1P0sLc5jG/h+R1Y=}
